# Generated by Django 2.0.7 on 2018-07-06 19:23

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('grading_system', '0002_student_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='assingment_date',
            new_name='assignment_date',
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=models.CharField(max_length=60)),
        ),
        migrations.AlterField(
            model_name='assignmentresult',
            name='grade',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
