# Generated by Django 2.0.7 on 2018-07-07 10:19

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('grading_system', '0003_auto_20180706_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name']),
        ),
    ]
