# Generated by Django 2.0.7 on 2018-07-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading_system', '0004_auto_20180707_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentresult',
            name='comments',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
