# Generated by Django 2.0.7 on 2018-07-19 01:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grading_system', '0005_auto_20180707_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentgroup',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_groups', to='grading_system.Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studenenrollment',
            name='grade',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='studenenrollment',
            name='partial_grades',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='studenenrollment',
            unique_together={('student', 'course')},
        ),
    ]
