# Generated by Django 2.0.7 on 2018-07-29 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grading_system', '0006_auto_20180719_0145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudenEnrollment',
            new_name='StudentEnrollment',
        ),
    ]
